import type { Metadata } from "next";
import { GuideExample, PublicGuide } from "../components/public-guide";

export const metadata: Metadata = {
  title: "Coffee Brew Log: What to Record and What to Skip",
  description: "Create a practical coffee brew log for espresso, pour-over, automatic machines, or capsules. Record the settings, outcomes, and next change that matter.",
  alternates: { canonical: "/brew-log" },
  openGraph: { title: "Coffee Brew Log: What to Record and What to Skip", description: "A practical brew log for espresso, pour-over, automatic machines, and everyday coffee.", url: "/brew-log", type: "article", publishedTime: "2026-09-12" },
  twitter: { card: "summary", title: "Coffee Brew Log: What to Record and What to Skip", description: "Settings, outcomes, taste, and the next change—without unnecessary fields." },
};

const sections = [["minimum-log", "Minimum log"], ["settings-outcomes", "Settings vs outcomes"], ["method-fields", "Method-aware fields"], ["examples", "Examples"], ["next-brew", "Improve the next brew"]] as const;

export default function BrewLogPage() {
  return <PublicGuide title="What to Record in a" titleAccent="Coffee Brew Log" description={metadata.description as string} route="/brew-log" sections={[...sections]} ctaKicker="Make the next cup easier" ctaTitle="Remember which setting worked." ctaDescription="Keep each coffee’s brews together, compare the results, and carry the useful parts into your next cup." ctaLabel="Start a free brew journal">
    <p className="article-opening">A coffee brew log should answer two questions: what happened, and what should I repeat or change next time?</p>
    <p>It does not need every possible measurement. A useful log keeps the coffee, the controllable settings, the observed result, and your reaction connected. The fields should change with the method: water temperature may matter for pour-over, while a capsule user should not be asked for a grinder setting.</p>
    <section className="article-answer" aria-label="The short answer"><span>The short answer</span><p>Record the coffee, date, method, liking, the settings you controlled, the result you observed, and one next action. Leave irrelevant fields empty.</p></section>

    <section id="minimum-log"><p className="article-section-number">01</p><h2>The minimum useful brew log</h2><p>Start with five pieces of information:</p><ol><li>the coffee product;</li><li>the brew method and date;</li><li>one or two settings you controlled;</li><li>how much you liked the result;</li><li>what you would keep or change.</li></ol><p>This is enough to build continuity. Add more numbers only when you will use them to compare brews.</p><GuideExample rows={[["Coffee", "Highland espresso · medium roast"], ["Method", "Espresso machine"], ["Setting", "Grind 7 · dose 18 g"], ["Outcome", "36 g espresso · 29 seconds"], ["Result", "8/10 · sweet and balanced"], ["Next", "Keep this setting"]]} className="journal-example-compact" /></section>

    <section id="settings-outcomes"><p className="article-section-number">02</p><h2>Separate settings from outcomes</h2><p>A common logging mistake is treating every number as a recipe target. Some values are choices you make before brewing; others are what the machine or brew produces.</p><h3>Settings you may control</h3><ul><li>grind setting;</li><li>coffee dose;</li><li>water temperature for a manual brew;</li><li>brew program or cup size;</li><li>the amount and type of milk.</li></ul><h3>Outcomes you observe</h3><ul><li>actual beverage yield;</li><li>actual extraction or brew time;</li><li>flow behavior;</li><li>taste and liking.</li></ul><p>If your last espresso produced 36 g in 29 seconds, copying the grind and dose can make sense. Copying “29 seconds” as though it were a setting does not guarantee the same result. Record it again after the next shot.</p><blockquote>Start from the last brew’s settings. Measure the next brew’s outcomes again.</blockquote></section>

    <section id="method-fields"><p className="article-section-number">03</p><h2>Only ask for method-relevant fields</h2><p>A single universal form quickly becomes cluttered. Use the method to decide what matters.</p><GuideExample rows={[["Espresso", "Grind · dose · actual yield · actual time"], ["Pour-over", "Grind · coffee and water amount · temperature · brew time"], ["Automatic machine", "Program · strength setting · drink · milk, when relevant"], ["Capsule", "Capsule · cup program · drink · liking"], ["Café drink", "Café · coffee or drink name · milk · personal note"]]} /><p>Machine and grinder usually belong to your saved equipment setup rather than being re-entered for every cup. Keep a snapshot with the historical record, but show it only when it changed or helps explain the result.</p></section>

    <section id="examples"><p className="article-section-number">04</p><h2>Two brew log examples</h2><h3>Espresso with milk</h3><GuideExample rows={[["Coffee", "Seasonal espresso blend"], ["Equipment", "Compact espresso machine · built-in grinder"], ["Settings", "Grind 6 · 18 g dose"], ["Outcomes", "38 g yield · 27 seconds"], ["Drink", "Cappuccino · oat milk · 90 ml"], ["Taste", "7.5/10 · chocolatey, balanced, slightly dry"], ["Next", "Keep grind · use slightly less milk"]]} className="journal-example-espresso" /><h3>V60 pour-over</h3><GuideExample rows={[["Coffee", "Washed Ethiopian coffee"], ["Settings", "Grind 22 · 15 g coffee · 250 g water · 93°C"], ["Outcome", "2 minutes 48 seconds"], ["Taste", "8/10 · floral, citrus, tea-like body"], ["Next", "Repeat before changing anything"]]} /><p className="article-note"><strong>Numbers are equipment-specific:</strong> grind 22 has no universal meaning. It is useful only when compared with the same grinder.</p></section>

    <section id="next-brew"><p className="article-section-number">05</p><h2>Turn every entry into one next step</h2><p>When a brew disappoints, avoid changing grind, dose, yield, and temperature together. Choose one controllable variable, keep the others stable, and record the result. If the cup is good, “keep setting” is a valid next action.</p><p>Not every coffee can be adjusted into a favorite. If several reasonable attempts still produce a cup you dislike, mark the coffee “not for me.” That decision is useful preference evidence even if the final score was not extremely low.</p><p>A brew log focuses on preparation and results. To connect those entries to a longer personal history, see the <a href="/coffee-journal">personal coffee journal guide</a>. To describe the cup without expert vocabulary, use the <a href="/coffee-tasting-notes">coffee tasting notes guide</a>.</p></section>
  </PublicGuide>;
}
