import type { Metadata } from "next";
import { GuideExample, PublicGuide } from "../components/public-guide";

export const metadata: Metadata = {
  title: "How to Discover Your Coffee Taste Without a Quiz",
  description: "Discover which coffee you actually enjoy by comparing real cups, sensory patterns, brew context, favorites, and honest not-for-me decisions.",
  alternates: { canonical: "/discover-your-coffee-taste" },
  openGraph: { title: "How to Discover Your Coffee Taste Without a Quiz", description: "A practical way to learn your coffee preferences from real cups instead of labels or quizzes.", url: "/discover-your-coffee-taste", type: "article", publishedTime: "2026-09-12" },
  twitter: { card: "summary", title: "How to Discover Your Coffee Taste Without a Quiz", description: "Learn from repeated cups, honest liking, and clear decisions." },
};

const sections = [["taste-not-label", "Taste is not a label"], ["collect-evidence", "Collect evidence"], ["compare-patterns", "Compare patterns"], ["context", "Keep context"], ["use-the-result", "Use what you learn"]] as const;

export default function DiscoverTastePage() {
  return <PublicGuide title="How to Discover" titleAccent="the Coffee You Actually Like" description={metadata.description as string} route="/discover-your-coffee-taste" sections={[...sections]} ctaKicker="Let your taste take shape" ctaTitle="Learn from the coffees you really drink." ctaDescription="Record a few honest cups and begin seeing the sensory qualities, flavors, and coffee styles you return to." ctaLabel="Discover my coffee taste">
    <p className="article-opening">You do not discover your coffee taste by choosing “fruity” or “chocolatey” in a quiz. You discover it by remembering real cups, honest reactions, and the conditions around them.</p>
    <p>Your preference can include apparent contradictions. You may like bright washed coffees as pour-over, dislike sharp acidity in espresso, and still enjoy a citrusy coffee with milk. The goal is not to force yourself into one category. It is to make the next purchase or brew easier.</p>
    <section className="article-answer" aria-label="The short answer"><span>The short answer</span><p>Record liking and sensory character separately, compare several coffees, keep context, and treat both favorites and “not for me” decisions as useful evidence.</p></section>

    <section id="taste-not-label"><p className="article-section-number">01</p><h2>Your taste is a pattern, not a personality type</h2><p>Words such as “bright,” “classic,” “fruity,” and “bold” are shortcuts. They can help you search, but they are not complete profiles. A useful preference statement is more specific:</p><blockquote>I usually enjoy sweet, medium-bodied espresso with low-to-moderate acidity, especially with oat milk.</blockquote><p>That sentence connects character, method, and context. It can change as you try more coffees.</p><p>Avoid turning reference descriptions into personal facts. A roaster may call a coffee low-acidity while you repeatedly experience it as sharp. Keep the description and your perception separate.</p></section>

    <section id="collect-evidence"><p className="article-section-number">02</p><h2>Collect small pieces of evidence</h2><p>You do not need a professional tasting routine. For each meaningful coffee experience, record:</p><ul><li>which coffee it was;</li><li>how much you liked it;</li><li>one or two sensory impressions;</li><li>the method or drink context;</li><li>whether you would buy it again.</li></ul><p>Use a liking scale consistently enough for comparison. A 5.5 or 6 does not necessarily mean a coffee belongs in your preferred profile. If you have decided “not for me” after fair attempts, keep that decision visible rather than allowing a passable score to describe what you seek.</p><GuideExample rows={[["Coffee A", "8.5/10 · bright, floral · V60 · buy again"], ["Coffee B", "6/10 · sharp citrus · espresso · not for me"], ["Coffee C", "8/10 · chocolate, creamy · cappuccino · favorite"], ["Coffee D", "7.5/10 · juicy, sweet · AeroPress · buy again"]]} /></section>

    <section id="compare-patterns"><p className="article-section-number">03</p><h2>Compare groups, not isolated scores</h2><p>After five to ten coffees, group your notes in several ways:</p><ul><li>coffees you would buy again versus those you would not;</li><li>espresso, filter, automatic machine, capsule, or café drinks;</li><li>black coffee versus milk drinks;</li><li>the sensory qualities you explicitly noticed;</li><li>origin, roast, or flavor information when it is available.</li></ul><p>Look for repeated relationships. Maybe higher-acidity coffees score well as filter but poorly as espresso. Maybe milk compatibility matters more to you than origin. Maybe you enjoy “nutty” coffees only when they also feel naturally sweet.</p><h3>Use six dimensions only when you noticed them</h3><p>Beanmemo can compare acidity, natural sweetness, bitterness, body, aroma, and balance. Its Taste Radar summarizes explicitly recorded sensory observations rather than filling empty dimensions with invented defaults.</p><p>A profile based on four honest observations is more trustworthy than a complete-looking chart made from guesses. Personal liking also stays separate: intensity and enjoyment are not the same thing.</p></section>

    <section id="context"><p className="article-section-number">04</p><h2>Keep enough context to explain exceptions</h2><p>Preparation changes perception. A brew that runs too quickly may taste very different from the same coffee under a better setting. Save the settings and outcomes that matter to your method so you can tell a product preference from a one-off result.</p><p>At the same time, do not assume every dislike is a technical failure. If your machine is already adjusted sensibly and repeated cups remain unpleasant, “I do not like this coffee” is a legitimate conclusion.</p><GuideExample rows={[["Reference", "Low acidity · milk chocolate · nutty"], ["Repeated perception", "High acidity across three espresso brews"], ["Context", "Grind adjusted finer; extraction time increased"], ["Decision", "Not for me on this setup"], ["Meaning", "Personal evidence, not a global correction to the coffee"]]} className="journal-example-compact" /></section>

    <section id="use-the-result"><p className="article-section-number">05</p><h2>Turn your taste into better decisions</h2><p>A useful preference profile should help you:</p><ul><li>choose between two coffees before buying;</li><li>recognize flavor descriptions that often work for you;</li><li>select a method that suits a coffee and your habits;</li><li>remember why a previous bag was a favorite;</li><li>avoid repeating purchases you already judged “not for me.”</li></ul><p>Keep the conclusion human-readable. “You often enjoy sweet, medium-roast coffees with chocolate or nut flavors as milk drinks” is more actionable than a radar with unexplained numbers.</p><p>Begin by keeping <a href="/coffee-tasting-notes">plain-language tasting notes</a>. Use a <a href="/coffee-bean-tracker">coffee bean tracker</a> to preserve favorites, finished coffees, and repurchase decisions.</p></section>
  </PublicGuide>;
}
