import type { Metadata } from "next";
import { GuideExample, PublicGuide } from "../components/public-guide";

export const metadata: Metadata = {
  title: "Coffee Tasting Notes: A Simple Guide for Beginners",
  description: "Learn how to write useful coffee tasting notes in plain language, separate the bag description from your own experience, and remember what you liked.",
  alternates: { canonical: "/coffee-tasting-notes" },
  openGraph: { title: "Coffee Tasting Notes: A Simple Guide for Beginners", description: "A practical, plain-language method for noticing and remembering coffee taste.", url: "/coffee-tasting-notes", type: "article", publishedTime: "2026-09-12" },
  twitter: { card: "summary", title: "Coffee Tasting Notes: A Simple Guide for Beginners", description: "Notice what matters in the cup without turning coffee into an exam." },
};

const sections = [["start-simple", "Start simple"], ["three-questions", "Three questions"], ["reference-vs-you", "Bag vs cup"], ["quick-template", "Quick template"], ["compare-notes", "Learn over time"]] as const;

export default function CoffeeTastingNotesPage() {
  return <PublicGuide title="How to Take Coffee Tasting Notes" titleAccent="Without Expert Vocabulary" description={metadata.description as string} route="/coffee-tasting-notes" sections={[...sections]} ctaKicker="Keep your own tasting language" ctaTitle="Remember what you actually tasted." ctaDescription="Save what the bag says, what you noticed in the cup, and whether you would choose the coffee again." ctaLabel="Start taking coffee notes">
    <p className="article-opening">Coffee tasting notes are useful when they help you remember a cup—not when they make you worry about finding the “correct” flavor.</p>
    <p>A bag may promise jasmine, peach, and bergamot while you taste sharp citrus and very little sweetness. That difference is information. The roaster’s description records one reference experience; your note records what happened in your cup, with your water, equipment, recipe, and senses.</p>
    <section className="article-answer" aria-label="The short answer"><span>The short answer</span><p>Record how much you liked the coffee, what stood out, the context in which you drank it, and one decision for next time. Plain, honest language is more useful than a list of flavors you did not really taste.</p></section>

    <section id="start-simple"><p className="article-section-number">01</p><h2>Start with recognition, not identification</h2><p>You do not need to identify a specific fruit. Begin with contrasts that are easier to notice:</p><ul><li>bright or mellow;</li><li>sweet or dry;</li><li>pleasantly bitter or harsh;</li><li>light, creamy, or heavy;</li><li>clean or lingering.</li></ul><p>“Fresh and bright, like biting into a green apple” is useful. “Too sour for me after it cooled” is equally useful. Both describe an experience you can compare later.</p><p className="article-note"><strong>Keep liking separate:</strong> a coffee can be intensely acidic and still be your favorite. Record the character of the cup and your enjoyment as two different answers.</p></section>

    <section id="three-questions"><p className="article-section-number">02</p><h2>Use three intuitive taste questions</h2><p>For a quick note, acidity, bitterness, and natural sweetness are usually easier to understand than professional scoring categories.</p><h3>Acidity: how bright or sharp does it feel?</h3><p>Low acidity may feel mellow or soft. Higher acidity may feel lively, juicy, tart, or sharply sour. Acidity is not automatically good or bad; write how it felt to you.</p><h3>Bitterness: pleasant structure or distraction?</h3><p>Some bitterness can make espresso or dark-roasted coffee feel satisfying. Note whether it was cocoa-like and pleasant, dry, burnt, or overwhelming.</p><h3>Natural sweetness: did the cup feel rounded?</h3><p>Coffee sweetness does not need to taste like added sugar. It may remind you of caramel, ripe fruit, honey, or simply a smooth finish without harsh edges.</p><p>Body, aroma, and balance can add detail when you notice them. They do not need to be mandatory. If “body” feels abstract, describe mouthfeel instead: tea-like, silky, creamy, syrupy, or heavy.</p></section>

    <section id="reference-vs-you"><p className="article-section-number">03</p><h2>Keep “the bag says” separate from “I tasted”</h2><p>Copying the printed flavor notes can help identify a coffee, but it should not replace your own observation. Store both layers:</p><GuideExample rows={[["Bag description", "Floral · stone fruit · caramel"], ["What I noticed", "Bright citrus · gentle sweetness · tea-like body"], ["Brew context", "V60 · 15 g coffee · 250 g water · 2:48"], ["Liking", "8 / 10"], ["Next time", "Repeat before changing the recipe"]]} className="journal-example-espresso" /><p>The disagreement does not prove that the roaster is wrong or that you brewed badly. It gives you a question worth testing. If the same difference appears across several brews, it becomes a meaningful pattern about this coffee, your setup, or your sensitivity.</p></section>

    <section id="quick-template"><p className="article-section-number">04</p><h2>A 15-second tasting note template</h2><p>Use this after a first cup, a meaningful recipe change, or any coffee you want to remember:</p><GuideExample rows={[["Liking", "__/10"], ["Taste", "Bright / mellow · sweet / dry · pleasant / harsh bitterness"], ["My words", "It reminds me of __________"], ["Decision", "Repeat · adjust · buy again · not for me"]]} className="journal-example-compact" /><p>If you have more time, add body, aroma, balance, and a free sentence. Missing detail is better than a default rating you did not actually choose.</p><blockquote>A short honest note is more valuable than six invented scores.</blockquote></section>

    <section id="compare-notes"><p className="article-section-number">05</p><h2>Compare several notes before defining your taste</h2><p>One unusual brew can reflect a recipe problem. Look for repeated signals across coffees and contexts. Do the coffees you rate highly tend to feel bright or mellow? Do you enjoy chocolate-like bitterness in espresso but dislike sharp acidity in milk drinks? Are fruity coffees more appealing as filter coffee?</p><p>Review the notes attached to coffees you loved, coffees you finished without enthusiasm, and coffees you marked “not for me.” Your taste is not one radar score. It is a growing collection of preferences, exceptions, and context.</p><p>For a broader habit that connects products, brews, and decisions, read <a href="/coffee-journal">how to keep a coffee journal you will actually use</a>. For recipe-focused comparisons, use the <a href="/brew-log">coffee brew log guide</a>.</p></section>
  </PublicGuide>;
}
